"""Attendance service — smart check-in / check-out logic."""

from repositories.attendance_repository import (
    get_today_record,
    insert_check_in,
    update_check_out,
    get_attendance_report,
    get_attendance_report_range,
    get_attendance_summary,
    _get_empcode,
)


def smart_mark_attendance(card_no: str, attendance_type: str = "check_in", **kwargs):
    """
    Smart attendance logic (IN = earliest mark, OUT = latest mark):
      1. No record / no IN yet     → CHECK IN  (sets IN_TIME)
      2. Has an IN                 → CHECK OUT (extends OUT_TIME to this, the
                                     latest, mark — so repeat or accidental marks
                                     only push OUT forward; IN stays the earliest)
    """
    record = get_today_record(card_no)

    _checkin_kwargs = dict(
        card_no=card_no,
        empcode=_get_empcode(card_no),
        latitude=kwargs.get("latitude"),
        longitude=kwargs.get("longitude"),
        accuracy=kwargs.get("accuracy"),
        address=kwargs.get("address"),
        formatted_address=kwargs.get("formatted_address"),
        timestamp=kwargs.get("timestamp"),
        device_id=kwargs.get("device_id"),
        device_model=kwargs.get("device_model"),
        app_version=kwargs.get("app_version"),
        attendance_type=attendance_type,
    )

    if record is None:
        # No roster row at all → insert check-in
        print(f"[ATTENDANCE] card={card_no} → no record today, checking in")
        return insert_check_in(**_checkin_kwargs)

    entry = record["entry_time"]   # "" when IN_TIME is NULL in DB
    exit_ = record["exit_time"]    # "" when OUT_TIME is NULL in DB

    if entry:
        # Already has an IN → this (later) mark becomes/extends the check-out.
        # update_check_out keeps the LATEST of the existing OUT and now, so a
        # second accidental tap and a real evening checkout both resolve to the
        # correct max OUT (and IN remains the earliest mark).
        print(f"[ATTENDANCE] card={card_no} → has entry ({entry}, out={exit_ or '-'}), updating check-out")
        # Store the location sent with THIS (check-out) mark in the dedicated
        # checkout columns — keep the richer formatted address when available.
        co_addr = kwargs.get("formatted_address") or kwargs.get("address")
        return update_check_out(
            record["id"], entry,
            card_no=record.get("card_no", card_no),
            source=record.get("source", "attendance_records"),
            current_out=exit_ or None,
            checkout_lat=kwargs.get("latitude"),
            checkout_long=kwargs.get("longitude"),
            checkout_address=co_addr,
        )

    # Roster row exists but IN_TIME is empty (pre-generated by ZK roster, no clock-in yet)
    print(f"[ATTENDANCE] card={card_no} → roster row exists but no IN_TIME, checking in")
    return insert_check_in(**_checkin_kwargs)


def fetch_attendance_report(card_no: str, date_str: str):
    return get_attendance_report(card_no, date_str)


def fetch_attendance_report_range(card_no: str, from_date: str, to_date: str):
    return get_attendance_report_range(card_no, from_date, to_date)


def fetch_attendance_summary(card_no: str, from_date: str, to_date: str):
    return get_attendance_summary(card_no, from_date, to_date)
